"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useFieldArray, useForm } from "react-hook-form";
import { z } from "zod";
import { useEffect, useMemo, useState } from "react";
import { Eye, Plus, Save, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api-client";
import { useProjects, useSaveSkill, useSkill } from "@/lib/hooks";
import type { SkillInput } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ErrorState } from "@/components/data-state";

const stepSchema = z.object({ id: z.string(), position: z.number(), title: z.string().min(1, "Title is required"), instruction: z.string().min(1, "Instruction is required"), condition: z.string(), is_required: z.boolean(), expected_result: z.string() });
const toolSchema = z.object({ id: z.string(), tool_name: z.string().min(1), tool_namespace: z.string(), requirement: z.enum(["required", "optional"]), purpose: z.string(), usage_hint: z.string() });
const contextSchema = z.object({ id: z.string(), type: z.string().min(1), query: z.string().min(1), description: z.string(), required: z.boolean(), priority: z.number(), max_tokens: z.number().optional() });
const dependencySchema = z.object({ id: z.string(), depends_on_skill_id: z.string().min(1), type: z.string().min(1), position: z.number() });
const exampleSchema = z.object({ id: z.string(), title: z.string().min(1), input_example: z.string().min(1), expected_behavior: z.string().min(1), bad_behavior: z.string(), priority: z.number() });
const formSchema = z.object({
  id: z.string().optional(), mcp_project: z.string().min(1, "Project is required"), slug: z.string().min(2).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase kebab-case"), name: z.string().min(2), description: z.string().min(3), purpose: z.string().min(3), when_to_use: z.string().min(3), when_not_to_use: z.string(), instructions: z.string().min(3), success_criteria_text: z.string().min(1), scope: z.enum(["global", "workspace", "project"]), status: z.enum(["draft", "active", "deprecated", "archived"]), priority: z.coerce.number().int(), domains_text: z.string(), intents_text: z.string(), object_types_text: z.string(), tags_text: z.string(), keywords_text: z.string(), capabilities_text: z.string(), compatibility_text: z.string(), steps: z.array(stepSchema), tools: z.array(toolSchema), contexts: z.array(contextSchema), dependencies: z.array(dependencySchema), examples: z.array(exampleSchema)
});
type FormValues = z.infer<typeof formSchema>;
const split = (value: string) => value.split(/[,\n]/).map((item) => item.trim()).filter(Boolean);
const defaults: FormValues = { mcp_project: "", slug: "", name: "", description: "", purpose: "", when_to_use: "", when_not_to_use: "", instructions: "", success_criteria_text: "", scope: "project", status: "draft", priority: 0, domains_text: "", intents_text: "", object_types_text: "", tags_text: "", keywords_text: "", capabilities_text: "", compatibility_text: "", steps: [], tools: [], contexts: [], dependencies: [], examples: [] };

function toInput(values: FormValues, original?: Awaited<ReturnType<typeof api.getSkill>>): SkillInput {
  return { id: values.id, mcp_project: values.mcp_project, current_version: original?.current_version, slug: values.slug, name: values.name, description: values.description, purpose: values.purpose, when_to_use: values.when_to_use, when_not_to_use: values.when_not_to_use, instructions: values.instructions, success_criteria: split(values.success_criteria_text), scope: values.scope, status: values.status, priority: values.priority, domains: split(values.domains_text), intents: split(values.intents_text), object_types: split(values.object_types_text), tags: split(values.tags_text), keywords: split(values.keywords_text), capabilities: split(values.capabilities_text), compatibility: split(values.compatibility_text), steps: values.steps, tools: values.tools, context_requirements: values.contexts, dependencies: values.dependencies, examples: values.examples };
}
function fromSkill(skill: Awaited<ReturnType<typeof api.getSkill>>): FormValues { return { id: skill.id, mcp_project: skill.mcp_project, slug: skill.slug, name: skill.name, description: skill.description, purpose: skill.purpose, when_to_use: skill.when_to_use, when_not_to_use: skill.when_not_to_use ?? "", instructions: skill.instructions, success_criteria_text: skill.success_criteria.join("\n"), scope: skill.scope, status: skill.status, priority: skill.priority, domains_text: skill.domains.join(", "), intents_text: skill.intents.join(", "), object_types_text: skill.object_types.join(", "), tags_text: skill.tags.join(", "), keywords_text: skill.keywords.join(", "), capabilities_text: skill.capabilities.join(", "), compatibility_text: skill.compatibility.join(", "), steps: skill.steps.map((step) => ({ ...step, condition: step.condition ?? "", expected_result: step.expected_result ?? "" })), tools: skill.tools.map((tool) => ({ ...tool, tool_namespace: tool.tool_namespace ?? "", purpose: tool.purpose ?? "", usage_hint: tool.usage_hint ?? "" })), contexts: skill.context_requirements.map((context) => ({ ...context, description: context.description ?? "" })), dependencies: skill.dependencies, examples: skill.examples.map((example) => ({ ...example, bad_behavior: example.bad_behavior ?? "" })) }; }

export function SkillForm({ skillId }: { skillId?: string }) {
  const router = useRouter();
  const existing = useSkill(skillId ?? "");
  const projects = useProjects();
  const mutation = useSaveSkill();
  const [preview, setPreview] = useState<string | null>(null);
  const storageKey = `skillbox:draft:${skillId ?? "new"}`;
  const form = useForm<FormValues>({ resolver: zodResolver(formSchema), defaultValues: defaults, mode: "onChange" });
  const steps = useFieldArray({ control: form.control, name: "steps" });
  const tools = useFieldArray({ control: form.control, name: "tools" });
  const contexts = useFieldArray({ control: form.control, name: "contexts" });
  const dependencies = useFieldArray({ control: form.control, name: "dependencies" });
  const examples = useFieldArray({ control: form.control, name: "examples" });
  useEffect(() => {
    if (existing.data) { form.reset(fromSkill(existing.data)); return; }
    if (!skillId) { const saved = localStorage.getItem(storageKey); if (saved) { try { form.reset(formSchema.parse(JSON.parse(saved))); toast.info("Локальный черновик восстановлен"); } catch { localStorage.removeItem(storageKey); } } }
  }, [existing.data, form, skillId, storageKey]);
  useEffect(() => {
    if (!skillId && !form.getValues("mcp_project") && projects.data?.length) {
      form.setValue("mcp_project", projects.data[0].external_id || projects.data[0].slug);
    }
  }, [form, projects.data, skillId]);
  useEffect(() => { const subscription = form.watch((value) => localStorage.setItem(storageKey, JSON.stringify(value))); return () => subscription.unsubscribe(); }, [form, storageKey]);
  const submit = form.handleSubmit(async (values) => {
    try { const saved = await mutation.mutateAsync(toInput(values, existing.data)); localStorage.removeItem(storageKey); toast.success(saved.id === skillId ? "Skill updated" : "Draft created"); router.push(`/skills/view?id=${encodeURIComponent(saved.id)}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Save failed"); }
  });
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void submit(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [submit]);
  const fieldError = useMemo(() => Object.values(form.formState.errors)[0]?.message, [form.formState.errors]);
  if (existing.error || projects.error) return <ErrorState error={(existing.error ?? projects.error) as Error} />;
  return <form onSubmit={submit} className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">{form.formState.isDirty ? "Unsaved changes · autosaved locally" : "All changes saved locally"}</p>{fieldError && <p className="text-xs text-destructive">{String(fieldError)}</p>}</div><div className="flex gap-2"><Button type="button" variant="outline" onClick={() => setPreview(form.getValues("instructions"))}><Eye className="size-4" />Preview</Button><Button type="submit" disabled={mutation.isPending}><Save className="size-4" />Save draft</Button></div></div>
    <Card><CardHeader><CardTitle>Basic information</CardTitle><CardDescription>Identity and selection cues used by agents.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Project" error={form.formState.errors.mcp_project?.message}>{skillId ? <><input type="hidden" {...form.register("mcp_project")} /><Input value={existing.data?.project?.name ?? existing.data?.mcp_project ?? ""} disabled /></> : <Select {...form.register("mcp_project")}><option value="">Select project</option>{(projects.data ?? []).map((project) => <option key={project.id} value={project.external_id || project.slug}>{project.name}</option>)}</Select>}</Field><Field label="Name" error={form.formState.errors.name?.message}><Input {...form.register("name")} placeholder="Resolve current user identity" /></Field><Field label="Slug" error={form.formState.errors.slug?.message}><Input {...form.register("slug")} placeholder="current-user-identity" /></Field><Field className="md:col-span-2" label="Description"><Textarea {...form.register("description")} className="min-h-20" /></Field><Field label="Purpose"><Textarea {...form.register("purpose")} /></Field><Field label="When to use"><Textarea {...form.register("when_to_use")} /></Field><Field label="When not to use"><Textarea {...form.register("when_not_to_use")} /></Field><Field label="Success criteria (one per line)"><Textarea {...form.register("success_criteria_text")} /></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Metadata & lifecycle</CardTitle><CardDescription>Comma-separated values are normalized before saving.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><Field label="Scope"><Select {...form.register("scope")}><option value="project">Project</option><option value="workspace">Workspace</option><option value="global">Global</option></Select></Field><Field label="Status"><Select {...form.register("status")} disabled={!skillId}><option value="draft">Draft</option><option value="active">Active</option><option value="deprecated">Deprecated</option><option value="archived">Archived</option></Select></Field><Field label="Priority"><Input type="number" {...form.register("priority", { valueAsNumber: true })} /></Field>{[["Domains", "domains_text"], ["Intents", "intents_text"], ["Object types", "object_types_text"], ["Tags", "tags_text"], ["Keywords", "keywords_text"], ["Capabilities", "capabilities_text"], ["Compatibility", "compatibility_text"]].map(([label, name]) => <Field key={name} label={label}><Input {...form.register(name as keyof FormValues)} placeholder="comma, separated" /></Field>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Instructions</CardTitle><CardDescription>Markdown is preserved and compiled by SkillBox.</CardDescription></CardHeader><CardContent><Textarea {...form.register("instructions")} className="min-h-64 font-mono text-xs" placeholder="Describe the complete reusable procedure…" /></CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Steps</CardTitle><CardDescription>Ordered, independently verifiable actions.</CardDescription></div><Button type="button" variant="outline" size="sm" onClick={() => steps.append({ id: "", position: steps.fields.length + 1, title: "", instruction: "", condition: "", is_required: true, expected_result: "" })}><Plus className="size-4" />Add step</Button></CardHeader><CardContent className="space-y-3">{steps.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-[80px_1fr_1.5fr_auto]"><Field label="Position"><Input type="number" {...form.register(`steps.${index}.position`, { valueAsNumber: true })} /></Field><Field label="Title"><Input {...form.register(`steps.${index}.title`)} /></Field><Field label="Instruction"><Textarea className="min-h-20" {...form.register(`steps.${index}.instruction`)} /></Field><Button type="button" variant="ghost" size="icon" className="self-end" onClick={() => steps.remove(index)} aria-label="Remove step"><Trash2 className="size-4" /></Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...form.register(`steps.${index}.is_required`)} />Required</label><Field label="Condition" className="md:col-span-1"><Input {...form.register(`steps.${index}.condition`)} /></Field><Field label="Expected result" className="md:col-span-2"><Input {...form.register(`steps.${index}.expected_result`)} /></Field></div>)}</CardContent></Card>
    <DynamicSection title="Tools" description="Required and optional capabilities." onAdd={() => tools.append({ id: "", tool_name: "", tool_namespace: "", requirement: "required", purpose: "", usage_hint: "" })}>{tools.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-3"><Field label="Tool name"><Input {...form.register(`tools.${index}.tool_name`)} /></Field><Field label="Namespace"><Input {...form.register(`tools.${index}.tool_namespace`)} /></Field><Field label="Requirement"><Select {...form.register(`tools.${index}.requirement`)}><option value="required">Required</option><option value="optional">Optional</option></Select></Field><Field label="Purpose"><Input {...form.register(`tools.${index}.purpose`)} /></Field><Field label="Usage hint" className="md:col-span-2"><Input {...form.register(`tools.${index}.usage_hint`)} /></Field><RemoveButton onClick={() => tools.remove(index)} /></div>)}</DynamicSection>
    <DynamicSection title="Context requirements" description="Facts the agent must load before execution." onAdd={() => contexts.append({ id: "", type: "rag", query: "", description: "", required: true, priority: 0, max_tokens: undefined })}>{contexts.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-4"><Field label="Type"><Input {...form.register(`contexts.${index}.type`)} /></Field><Field label="Query" className="md:col-span-2"><Input {...form.register(`contexts.${index}.query`)} /></Field><Field label="Priority"><Input type="number" {...form.register(`contexts.${index}.priority`, { valueAsNumber: true })} /></Field><Field label="Description" className="md:col-span-2"><Input {...form.register(`contexts.${index}.description`)} /></Field><Field label="Max tokens"><Input type="number" {...form.register(`contexts.${index}.max_tokens`, { setValueAs: (value) => value === "" ? undefined : Number(value) })} /></Field><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" {...form.register(`contexts.${index}.required`)} />Required</label><RemoveButton onClick={() => contexts.remove(index)} /></div>)}</DynamicSection>
    <DynamicSection title="Dependencies" description="Other Skills required by this procedure." onAdd={() => dependencies.append({ id: "", depends_on_skill_id: "", type: "requires", position: dependencies.fields.length + 1 })}>{dependencies.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-[1fr_1fr_120px_auto]"><Field label="Skill ID"><Input {...form.register(`dependencies.${index}.depends_on_skill_id`)} /></Field><Field label="Type"><Input {...form.register(`dependencies.${index}.type`)} /></Field><Field label="Position"><Input type="number" {...form.register(`dependencies.${index}.position`, { valueAsNumber: true })} /></Field><RemoveButton onClick={() => dependencies.remove(index)} /></div>)}</DynamicSection>
    <DynamicSection title="Examples" description="Good and bad behavior for grounding." onAdd={() => examples.append({ id: "", title: "", input_example: "", expected_behavior: "", bad_behavior: "", priority: 0 })}>{examples.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-2"><Field label="Title"><Input {...form.register(`examples.${index}.title`)} /></Field><Field label="Priority"><Input type="number" {...form.register(`examples.${index}.priority`, { valueAsNumber: true })} /></Field><Field label="Input"><Textarea {...form.register(`examples.${index}.input_example`)} /></Field><Field label="Expected behavior"><Textarea {...form.register(`examples.${index}.expected_behavior`)} /></Field><Field label="Bad behavior" className="md:col-span-2"><Textarea {...form.register(`examples.${index}.bad_behavior`)} /></Field><RemoveButton onClick={() => examples.remove(index)} /></div>)}</DynamicSection>
    {preview !== null && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" onClick={() => setPreview(null)}><Card className="max-h-[80vh] w-full max-w-3xl overflow-auto" onClick={(event) => event.stopPropagation()}><CardHeader className="flex-row items-center justify-between"><CardTitle>Compiled preview</CardTitle><Button type="button" variant="ghost" onClick={() => setPreview(null)}>Close</Button></CardHeader><CardContent><pre className="whitespace-pre-wrap rounded-xl bg-muted p-4 text-sm">{preview || "No instructions yet."}</pre>{existing.data && <Button type="button" className="mt-4" onClick={async () => { try { const result = await api.prepareSkill(existing.data); setPreview(JSON.stringify(result.compiled_skill, null, 2)); } catch (error) { toast.error(error instanceof Error ? error.message : "Preview failed"); } }}><Send className="size-4" />Compile with SkillBox</Button>}</CardContent></Card></div>}
  </form>;
}

function Field({ label, error, className, children }: { label: string; error?: string; className?: string; children: React.ReactNode }) { return <label className={className}><span className="field-label">{label}</span>{children}{error && <span className="mt-1 block text-xs text-destructive">{error}</span>}</label>; }
function DynamicSection({ title, description, onAdd, children }: { title: string; description: string; onAdd: () => void; children: React.ReactNode }) { return <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></div><Button type="button" variant="outline" size="sm" onClick={onAdd}><Plus className="size-4" />Add</Button></CardHeader><CardContent className="space-y-3">{children}</CardContent></Card>; }
function RemoveButton({ onClick }: { onClick: () => void }) { return <Button type="button" variant="ghost" size="icon" className="self-end" onClick={onClick} aria-label="Remove item"><Trash2 className="size-4" /></Button>; }
